### ISSUE TITLE
Wondering which graphics did you experiment on? 

### ISSUE THREAD

**Issue by RorschachChen** [ZJZAC/Deep-Model-Watermarking#2]
Hi Dear ZJ, Great Work! I am trying to run with single RTX 2080Ti 11G, but the BatchSize I need to set as 2 to run, otherwise OOM problem is triggered? I noticed the BatchSize displayed in the code is 16.

**Comment by ZJZAC** [comment]
Hi Chen，Thanks for your interest to our work. We used 4 1080Ti/2080Ti in a parallel way to solve the OOM problem with BatchSize 16. BTW, the size of input image or the size of models can also be shrinked to overcome OOM.
