### ISSUE TITLE
about SR attack

### ISSUE THREAD

**Issue by Jayamoon59** [ZJZAC/Deep-Model-Watermarking#5]
Hi, I've been learning this code recently. I want you to ask me some questions.

At present, I run./SR attack, which uses derain treatment. The main problem is that I don't know what data sets are included in the training input. What's the output?

There is also a small problem in running./Initial stage. I input a color image, but the output is four lines of images, all of which are black and white.

I was hoping you could help me out.

**Comment by ZJZAC** [comment]
For the SR attack, we utilize the code of official pix2pix, which learns a supervised image-to-image task. The data shall be a pair of rainy image A and the watermarked derained image B' for deraining tasks. If you would like more details on constructing the dataset, you can refer to the paper.  

For initial training, the default setting is for debone task, therefore the output is a gray-scale image. You can easily change the[ pre-processing](https://github.com/ZJZAC/Deep-Model-Watermarking/blob/129120d060c7141fa538a5982ed10c894012252a/Initial%20stage/main.py#L174)  and [the input channel for Embedding Net](https://github.com/ZJZAC/Deep-Model-Watermarking/blob/129120d060c7141fa538a5982ed10c894012252a/Initial%20stage/main.py#L193) to adjust the deraining tasks.

Thanks for your interest in our work!
